name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  nix:
    name: fmt + vet + test (Nix)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: DeterminateSystems/nix-installer-action@07ebb8d2749aa2fac2baae7d1cfa011e4acfd8d1 # v5

      - name: Run fmt + vet + unit tests
        run: nix-build nix -A tests

  helm:
    name: Helm lint + template tests
    permissions:
      contents: read
    uses: ./.github/workflows/helm-lint.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha || github.sha }}
